#> This file gather elementary parameters and key for
#> more user frendly and efficient code.
#> You can direclty change parameters and key from
#> this file or use the user interface provided by SV

[VERSION]
version = 0.0.1

[USEFULL PATH]
input_path = ../input/
test_path = ../input/tests/
output_path = ../output/

[DIMENSION] (1 or 2)
Dimension = 1

[TEST CASE] (0: User define case, 1: case1, 2: case2)
Test_case_key = 0

[MESH TYPE] (0: User define mesh, 1: Strctured statical mesh, 2: Unstructered statical mesh)
Mesh_key = 1

[STRUCTURED STATICAL MESHGRID]
x_min = 0.0
y_min = 0.0
Lx = 25.0
Ly = 1.0
Nx = 100
Ny = 3

[TOPOGRAPHY FUNCTION] (0: User define function, 1: Const, 2: Sinus, 3: Bosse)
Topography_key = 3

[INITIAL CONDITION] (0: User define function, 1:Dame configuration, 2: Unique wave)
Initial_key = 1

[RIEMANN SCHEME] (1: HLL, 2: HLLC, 3: VFRoe)
R_Scheme_key = 1

[FINIT VOLUME SCHEME] (1: Berthon-Foucher)
FV_Scheme_key = 1

[END OF FILE]

