#> This file gather elementary parameters and key for
#> more user frendly and efficient code.
#> You can direclty change parameters and key from
#> this file or use the user interface provided by SV

[VERSION]
version = 0.0.1

[USEFULL PATH]
input_path = ../input/
test_path = ../input/tests/
output_path = ../output/

[DIMENSION] (1 or 2)
dim = 1

[MESH TYPE] (0: User define mesh, 1: Strctured statical mesh, 2: Unstructered statical mesh)
Mesh_key = 1

[STRUCTURED STATICAL MESHGRID]
x_min = -20.0
y_min = 0.0
Lx = 40.0
Ly = 1.0
Nx = 100
Ny = 3

[RIEMANN SCHEME] (1: Rusanov, 2: HLL, 3: VFRoe)
R_Scheme_key = 1

[FINIT VOLUME SCHEME] (1: Berthon-Foucher)
FV_Scheme_key = 1

[NUMERICAL TEST]
#> 1: Dam-break
#> 2: Subcritical and transcritical flow over a bump
#> 3: Streaming failure
#> 4: Discontinuous topography with resonant regime
#> 5: Thacker’s test
test_case = 1

[END OF FILE]

